/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as InformationRouteImport } from './routes/information'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AuthMicrosoftRouteImport } from './routes/auth.microsoft'
import { Route as AdminManageFeedbackRouteImport } from './routes/admin.manage-feedback'
import { Route as AuthMicrosoftStartRouteImport } from './routes/auth.microsoft.start'
import { Route as AuthMicrosoftCallbackRouteImport } from './routes/auth.microsoft.callback'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const InformationRoute = InformationRouteImport.update({
  id: '/information',
  path: '/information',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthMicrosoftRoute = AuthMicrosoftRouteImport.update({
  id: '/auth/microsoft',
  path: '/auth/microsoft',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManageFeedbackRoute = AdminManageFeedbackRouteImport.update({
  id: '/manage-feedback',
  path: '/manage-feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AuthMicrosoftStartRoute = AuthMicrosoftStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => AuthMicrosoftRoute,
} as any)
const AuthMicrosoftCallbackRoute = AuthMicrosoftCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthMicrosoftRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/information': typeof InformationRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/manage-feedback': typeof AdminManageFeedbackRoute
  '/auth/microsoft': typeof AuthMicrosoftRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/auth/microsoft/callback': typeof AuthMicrosoftCallbackRoute
  '/auth/microsoft/start': typeof AuthMicrosoftStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/feedback': typeof FeedbackRoute
  '/information': typeof InformationRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/manage-feedback': typeof AdminManageFeedbackRoute
  '/auth/microsoft': typeof AuthMicrosoftRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/auth/microsoft/callback': typeof AuthMicrosoftCallbackRoute
  '/auth/microsoft/start': typeof AuthMicrosoftStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/information': typeof InformationRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/manage-feedback': typeof AdminManageFeedbackRoute
  '/auth/microsoft': typeof AuthMicrosoftRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/auth/microsoft/callback': typeof AuthMicrosoftCallbackRoute
  '/auth/microsoft/start': typeof AuthMicrosoftStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/feedback'
    | '/information'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/manage-feedback'
    | '/auth/microsoft'
    | '/admin/'
    | '/auth/microsoft/callback'
    | '/auth/microsoft/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/feedback'
    | '/information'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/manage-feedback'
    | '/auth/microsoft'
    | '/admin'
    | '/auth/microsoft/callback'
    | '/auth/microsoft/start'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/feedback'
    | '/information'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/manage-feedback'
    | '/auth/microsoft'
    | '/admin/'
    | '/auth/microsoft/callback'
    | '/auth/microsoft/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  FeedbackRoute: typeof FeedbackRoute
  InformationRoute: typeof InformationRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthMicrosoftRoute: typeof AuthMicrosoftRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/information': {
      id: '/information'
      path: '/information'
      fullPath: '/information'
      preLoaderRoute: typeof InformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/microsoft': {
      id: '/auth/microsoft'
      path: '/auth/microsoft'
      fullPath: '/auth/microsoft'
      preLoaderRoute: typeof AuthMicrosoftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manage-feedback': {
      id: '/admin/manage-feedback'
      path: '/manage-feedback'
      fullPath: '/admin/manage-feedback'
      preLoaderRoute: typeof AdminManageFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/microsoft/start': {
      id: '/auth/microsoft/start'
      path: '/start'
      fullPath: '/auth/microsoft/start'
      preLoaderRoute: typeof AuthMicrosoftStartRouteImport
      parentRoute: typeof AuthMicrosoftRoute
    }
    '/auth/microsoft/callback': {
      id: '/auth/microsoft/callback'
      path: '/callback'
      fullPath: '/auth/microsoft/callback'
      preLoaderRoute: typeof AuthMicrosoftCallbackRouteImport
      parentRoute: typeof AuthMicrosoftRoute
    }
  }
}

interface AdminRouteChildren {
  AdminManageFeedbackRoute: typeof AdminManageFeedbackRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminManageFeedbackRoute: AdminManageFeedbackRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthMicrosoftRouteChildren {
  AuthMicrosoftCallbackRoute: typeof AuthMicrosoftCallbackRoute
  AuthMicrosoftStartRoute: typeof AuthMicrosoftStartRoute
}

const AuthMicrosoftRouteChildren: AuthMicrosoftRouteChildren = {
  AuthMicrosoftCallbackRoute: AuthMicrosoftCallbackRoute,
  AuthMicrosoftStartRoute: AuthMicrosoftStartRoute,
}

const AuthMicrosoftRouteWithChildren = AuthMicrosoftRoute._addFileChildren(
  AuthMicrosoftRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  FeedbackRoute: FeedbackRoute,
  InformationRoute: InformationRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthMicrosoftRoute: AuthMicrosoftRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
